name: build, test and deploy

on:
  push:
    branches:
      - 'master'
      - 'releases/**'
      - 'hotfix/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching all node_modules folder throughout repository
          path: '**/node_modules'
          # hashes all yarn.lock files to generate key
          key: ${{ runner.os }}-build-${{ env.cache-name }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-

      - name: install dependencies backend
        if: ${{ contains( ['both', 'backend'], secrets.PROJECT) }}
        run: yarn

      - name: install dependencies frontend
        if: ${{ contains( ['both', 'frontend'], secrets.PROJECT) }}
        run: cd client && yarn && cd ..
